#!/bin/sh

#output=/home/kshly/pictures/screenshots/"yump-$(date +%h%d_%H:%M:%S).png"

output=/home/kshly/pictures/screenshots/yum.png

menu() {
  echo "" | dmenu -p "Timer : " | xargs -I _ sleep "_"
}

case "$1" in
  "full") maim "$output" || exit;;
  "select") maim -s "$output" || exit;;
  "fulltime") menu && maim "$output" || exit;;
  "selecttime") menu && maim -s "$output" || exit;;

  esac

name=$(echo "" | dmenu -p "Name : ") && mv "$output" /home/kshly/pictures/screenshots/"$name".png


notify-send "Maim" "Sreenshot Taken, saved as "$name".png"
